package app.multiauth.config

/**
 * Generated OAuth configuration.
 * This file is generated by the Multi-Auth Gradle plugin.
 * Do not edit this file manually.
 */
object GeneratedOAuthConfig {
    // This will be replaced by the Gradle plugin with actual configuration
    val CONFIG_JSON = """
{
  "providers": {}
}
""".trimIndent()

    /**
     * Loads the generated OAuth configuration.
     */
    fun loadConfiguration() {
        OAuthConfigurationManager.loadConfiguration(CONFIG_JSON)
    }
}
